services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./watch/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./watch/prometheus:/prometheus
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.prometheus.rule=Host(`w.doany.io`)"
                - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
                - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    grafana:
        image: grafana/grafana
        volumes:
            - ./watch/grafana:/var/lib/grafana
        environment:
            - GF_SERVER_ROOT_URL=https://w.doany.io
            - GF_RENDERING_SERVER_URL=http://renderer:8081/render
            - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=
            - GF_SMTP_FROM_ADDRESS=
            - GF_SMTP_USER=
            - GF_SMTP_PASSWORD=
            - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=local
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.grafana.rule=Host(`w.daco.dev`)"
                - "traefik.http.routers.grafana.tls.certresolver=myresolver"
                - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    renderer:
        image: grafana/grafana-image-renderer
        environment:
            - BROWSER_TZ=Asia/Tokyo

networks:
    main_default:
        external: true
        name: main_default
